### ISSUE TITLE
Rewrite Tracking Issue

### ISSUE THREAD

**Issue by jay3332** [FerrisChat/Server#88]
This issue tracks the progress for the [rewrite](/tree/rewrite) branch. The branch will be merged once progress catches up with the [master](/#) branch; note that the master branch does not cover all bullet points listed here, so this may be merged even though all bullet points are not checked.

- [ ] Webserver
	- [ ] Authentication
		- [x] Login (POST `/login`)
		- [ ] Logout/Revoke Current Token (DELETE `/login`)
		- [ ] Verify Email (POST `/verify`)
	- [x] Users
		- [x] Register/Create User (POST `/users`)
		- [x] Get User (GET `/users/:id`)
		- [x] Get Current User (GET `/users/me`)
		- [x] Edit Current User (PATCH `/users/me`)
		- [x] Delete Account (DELETE `/users/me`)
	- [ ] Guilds
		- [x] Create Guild (POST `/guilds`)
		- [x] Get Guild (GET `/guilds/:id`)
		- [ ] Get All Guilds (GET `/guilds`)
		- [x] Edit Guild (PATCH `/guilds/:id`)
		- [x] Delete Guild (DELETE `/guilds/:id`)
	- [ ] Channels
		- [x] Create Guild Channel (POST `/guilds/:guild_id/channels`)
		- [ ] Open DM Channel (POST `/channels`)
		- [x] Get Channel (GET `/channels/:id`)
		- [x] Edit Channel (PATCH `/channels/:id`)
		- [ ] Edit Channel Positions (PATCH `/channels`)
		- [x] Delete Channel (DELETE `/channels/:id`)
		- [ ] Create Permission Overwrite (PUT `/channels/:id/overwrites/:target_id`)
		- [ ] Edit Permission Overwrite (PATCH `/channels/:channel_id/overwrites/:target_id`)
		- [ ] Delete Permission Overwrite (DELETE `/channels/:channel_id/overwrites/:target_id`)
		- [ ] Add User to Group DM (PUT `/channels/:id/recipients/:user_id`)
		- [ ] Remove User from Group DM (DELETE `/channels/:id/recipients/:user_id`)
		- [ ] Bulk Delete/Purge Messages (POST `/channels/:id/purge`)
		- [ ] Get Channel Message History (GET `/channels/:id/history`)
	- [ ] Messages
		- [ ] Send Message (POST `/channels/:channel_id/messages`)
		- [ ] Get Message (GET `/channels/:channel_id/messages/:id`)
		- [ ] Edit Message (PATCH `/channels/:channel_id/messages/:id`)
		- [ ] Delete Message (DELETE `/channels/:channel_id/messages/:id`)
		- [ ] Publish Announcement Message (POST `/channels/:channel_id/messages/:id/feed`)
		- [ ] Pin Message (PUT `/channels/:channel_id/pins/:message_id`)
		- [ ] Unpin Message (DELETE `channels/:channel_id/pins/:message_id`)
		- [ ] Add Reaction (PUT `/channels/:channel_id/messages/:id/reactions/:emoji`)
		- [ ] Remove Own Reaction (DELETE `/channels/:channel_id/messages/:id/reactions/:emoji/me`)
		- [ ] Remove Specific Reaction (DELETE `/channels/:channel_id/messages/:message_id/reactions/:emoji/:user_id`)
		- [ ] Remove All Reactions (DELETE `/channels/:channel_id/messages/:id/reactions`)
		- [ ] Get All Reactions (GET `/channels/:channel_id/messages/:id/reactions`)
	- [ ] Invites
		- [ ] Create Invite (POST `/guilds/:guild_id/invites`)
		- [ ] Get All Invites (GET `/guilds/:guild_id/invites`)
		- [ ] Revoke/Delete All Invites (DELETE `/guilds/:guild_id/invites`)
		- [ ] Use Invite/Join Guild via Invite (POST `/invites/:code`)
		- [ ] Revoke/Delete Invite (DELETE `/invites/:code`)
	- [ ] Applications/Bots
		- [ ] Get All Applications (GET `/apps`)
		- [ ] Get Application (GET `/apps/:id`)
		- [ ] Create Application (POST `/apps`)
		- [ ] Edit Application (PATCH `/apps/:id`)
		- [ ] Delete Application (DELETE `/apps/:id`)
		- [ ] Generate Bot Token (POST `/apps/:id/tokens`)
		- [ ] Get Guild Applications (GET `/guilds/:guild_id/apps`)
		- [ ] Add Application/Invite Bot (PUT `/guilds/:guild_id/apps/:id`)
		- [ ] Remove Application (DELETE `/guilds/:guild_id/apps/:id`)
	- [ ] Members
		- [ ] Get All Members (GET `/guilds/:guild_id/members`)
		- [ ] Get Member (GET `/guilds/:guild_id/members/:user_id`)
		- [ ] Edit Member (PATCH `/guilds/:guild_id/members/:user_id`)
		- [ ] Kick Member (DELETE `/guilds/:guild_id/members/:user_id`)
		- [ ] Ban Member (PUT `/guilds/:guild_id/bans/:user_id`)
		- [ ] Unban Member (DELETE `/guilds/:guild_id/bans/:user_id`)
	- [ ] Roles
		- [ ] Create Role (POST `/guilds/:guild_id/roles`)
		- [ ] Get All Roles (GET `/guilds/:guild_id/roles`)
		- [ ] Edit Role (PATCH `/guilds/:guild_id/roles/:id`)
		- [ ] Edit Role Hierarchy (PATCH `/guilds/:guild_id/roles`)
		- [ ] Delete Role (DELETE `/guilds/:guild_id/roles/:id`)
	- [ ] Starboard
		- [ ] Get Starboard Information (GET `/guilds/:guild_id/starboard`)
		- [ ] Get Recent Starred Messages (GET `/guilds/:guild_id/starboard/recent`)
		- [ ] Get Top Starred Messages (GET `/guilds/:guild_id/starboard/top`)
		- [ ] Get Starred Message History (GET `/guilds/:guild_id/starboard/messages`)
		- [ ] Star Message (PUT `/channels/:channel_id/messages/:message_id/stars`)
		- [ ] Unstar Message (DELETE `/channels/:channel_id/messages/:message_id/stars`)
		- [ ] Get Message Star Users (GET `/channels/:channel_id/messages/:message_id/stars/users`)
		- [ ] Remove All Stars from Message (DELETE `/channels/:channel_id/messages/:message_id/stars`)
	- [ ] 	TODO
- [ ] Websocket
	- [ ] Decide on which Message Broker to use:
		- RabbitMQ
		- Kafka 
		- Redis Pubsub
	- [ ] Webserver to Websocket Message Adapter Model
	- [ ] Websocket Events
		- [ ] TODO
- [ ] API Documentation
